<?php
/**
 * HD Account System — One-time setup script
 * SELF-DELETES after successful execution.
 * Access: https://valentinarussobg5.com/hd-setup.php?token=hd_setup_2026_vr
 */

header('Content-Type: application/json; charset=utf-8');

// ── Security token ───────────────────────────────────────────────────────────
$token = $_GET['token'] ?? '';
if (!hash_equals('hd_setup_2026_vr', $token)) {
    http_response_code(403);
    die(json_encode(['ok' => false, 'error' => 'Forbidden']));
}

$log = [];
$errors = [];

// ── Step 1: generate pepper ───────────────────────────────────────────────────
$pepper = bin2hex(random_bytes(32));
$log[] = 'Pepper generated: ' . substr($pepper, 0, 8) . '...';

// ── Step 2: write hd-db-config.php ───────────────────────────────────────────
$configPath = __DIR__ . '/hd-db-config.php';
$configContent = '<?php' . "\n" .
    '// HD Account System — DB Config (auto-generated by hd-setup.php)' . "\n" .
    "define('HD_DB_HOST',    'localhost');\n" .
    "define('HD_DB_NAME',    'valenti7_hd');\n" .
    "define('HD_DB_USER',    'valenti7_hduser');\n" .
    "define('HD_DB_PASS',    'y\$z4&qd{Bta%vsub');\n" .
    "define('HD_DB_PORT',    '3306');\n" .
    "define('HD_PEPPER',     '" . $pepper . "');\n" .
    "define('HD_BASE_URL',   'https://valentinarussobg5.com');\n" .
    "define('HD_FROM_EMAIL', 'noreply@valentinarussobg5.com');\n" .
    "define('HD_FROM_NAME',  'Valentina Russo');\n";

if (file_put_contents($configPath, $configContent) === false) {
    $errors[] = 'Cannot write hd-db-config.php';
} else {
    $log[] = 'hd-db-config.php written OK';
}

// ── Step 3: create DB tables ──────────────────────────────────────────────────
try {
    $pdo = new PDO(
        'mysql:host=localhost;dbname=valenti7_hd;charset=utf8mb4',
        'valenti7_hduser',
        'y$z4&qd{Bta%vsub',
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
    $log[] = 'DB connection OK';

    $pdo->exec("CREATE TABLE IF NOT EXISTS hd_users (
        id            INT UNSIGNED     AUTO_INCREMENT PRIMARY KEY,
        email         VARCHAR(254)     NOT NULL UNIQUE,
        password_hash VARCHAR(255)     NOT NULL,
        name          VARCHAR(100)     NOT NULL DEFAULT '',
        created_at    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
        verified_at   DATETIME         NULL,
        verify_token  VARCHAR(64)      NULL,
        reset_token   VARCHAR(64)      NULL,
        reset_expires DATETIME         NULL,
        session_ver   INT UNSIGNED     NOT NULL DEFAULT 0,
        gdpr_consent  TINYINT(1)       NOT NULL DEFAULT 0,
        gdpr_date     DATETIME         NULL,
        INDEX idx_email         (email),
        INDEX idx_verify_token  (verify_token),
        INDEX idx_reset_token   (reset_token)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $log[] = 'Table hd_users: OK';

    $pdo->exec("CREATE TABLE IF NOT EXISTS hd_charts (
        id           INT UNSIGNED     AUTO_INCREMENT PRIMARY KEY,
        user_id      INT UNSIGNED     NOT NULL,
        chart_name   VARCHAR(100)     NOT NULL DEFAULT 'Carta senza nome',
        birth_day    TINYINT UNSIGNED NOT NULL,
        birth_month  TINYINT UNSIGNED NOT NULL,
        birth_year   SMALLINT         NOT NULL,
        birth_hour   TINYINT UNSIGNED NOT NULL,
        birth_min    TINYINT UNSIGNED NOT NULL,
        birth_city   VARCHAR(150)     NOT NULL DEFAULT '',
        birth_tz     VARCHAR(60)      NOT NULL DEFAULT 'Europe/Rome',
        chart_json   MEDIUMTEXT       NOT NULL,
        created_at   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES hd_users(id) ON DELETE CASCADE,
        INDEX idx_user_created (user_id, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $log[] = 'Table hd_charts: OK';

    $pdo->exec("CREATE TABLE IF NOT EXISTS hd_login_attempts (
        id           INT UNSIGNED     AUTO_INCREMENT PRIMARY KEY,
        identifier   VARCHAR(64)      NOT NULL,
        attempted_at DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_identifier_time (identifier, attempted_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $log[] = 'Table hd_login_attempts: OK';

} catch (PDOException $e) {
    $errors[] = 'DB error: ' . $e->getMessage();
}

// ── Step 4: self-delete ───────────────────────────────────────────────────────
if (empty($errors)) {
    $log[] = 'Setup complete. Deleting self...';
    unlink(__FILE__);
    $log[] = 'Self-deleted OK';
}

// ── Response ──────────────────────────────────────────────────────────────────
echo json_encode([
    'ok'     => empty($errors),
    'log'    => $log,
    'errors' => $errors,
], JSON_PRETTY_PRINT);
